#ifndef HYPERBOREAN_ERRORS_HPP_INCLUDED
#define HYPERBOREAN_ERRORS_HPP_INCLUDED

#include <stdexcept>

namespace Hyperborean {
  // Base class for all exceptions generated by the game engine.
  class BaseError : public std::runtime_error {
    using std::runtime_error::runtime_error;
  };
}

#endif // HYPERBOREAN_ERRORS_HPP_INCLUDED
